### ISSUE TITLE
config.py file is missing?

### ISSUE THREAD

**Issue by kasri-mids** [LordMartian/deep_avsr#1]
Hi,
Happened to come by this repo and think this pretty awesome. Cant seem to locate the config.py file though. Was it intentional?

**Comment by LordMartian** [comment]
Hi,
Thanks for your interest. The config.py file keeps changing so it is currently added to the .gitignore. I will be adding the config.py in a couple of days.

**Comment by kasri-mids** [comment]
Thanks for the response! Any ideas of how I can run the demo? Is there a snapshot of config.py I can use to start playing with it? Looking to use my weekend on this :) Thanks again!

**Comment by LordMartian** [comment]
I can certainly provide you with a copy of the config.py file but you will need the pretrained model weights to generate valid predictions. Unfortunately I had to hold back the release of the pretrained models. Sorry for the confusion.

**Comment by LordMartian** [comment]
Attached is a zip file containing a copy of the config.py file.
[config.zip](https://github.com/LordMartian/deep_avsr/files/4874544/config.zip)

**Comment by kasri-mids** [comment]
Thanks!

**Comment by LordMartian** [comment]
I have added the config.py files.
