### ISSUE TITLE
When I was training the ao model,the WER and CER were always 1.000

### ISSUE THREAD

**Issue by liuzeyang0311** [lordmartian/deep_avsr#14]
When I was pretraining the ao model, the WER and CER were always 1.000.I printed the predictionbatch, and each predictionbatch is [39,39,39,39,39,39.39,39]or [1,39,1,39,1,39,1,39].Is that normal?

**Comment by lordmartian** [comment]
Please try the suggestions in #6. If the issue still persists then let me know.
