### ISSUE TITLE
When I train the ao model ,the WER and CER are always 1.

### ISSUE THREAD

**Issue by liuzeyang0311** [lordmartian/deep_avsr#15]
Thank you for your code,I was obsessed with this problem for days.
When I trained the ao model ,the WER and CER were always 1,and I printed the predictionbatch, and each predictionbatch is [39,39,39,39,39,39.39,39]or [1,39,1,39,1,39,1,39]. I tried to change the seed value but it didn't work. But when i trained the vo model
,it was normal.

**Comment by liuzeyang0311** [comment]
Excuse me.Do you know how I can solve this problem?

**Comment by lordmartian** [comment]
I have faced this issue a few times. But I don't have any exact answer for why it happens or how to solve it. You can try to make significant changes to the seed value (which has worked some times) or may be you can try using weight initializers like Xavier etc.

**Comment by lastlap** [comment]
I had this issue a few times, reducing the learning rate solved it once.
