### ISSUE TITLE
preprocess for lrs2 dataset

### ISSUE THREAD

**Issue by javadpeyman** [lordmartian/deep_avsr#16]
hi, which face detector and face aliment are used in lrs2 and lrs3 dataset?

**Comment by lordmartian** [comment]
Hi,
I do not use any face detector or face alignment during preprocessing as the face (more specifically the lip region) is already centered in LRS2 samples. Also, as per my observations, all frames in the dataset contain a face. So, I just take the central crop of size 112x112 from each frame during preprocessing. 
If you want to use a face detector/alignment, you can try the `dlib` python package.

**Comment by javadpeyman** [comment]
thank you so so so much.
