### ISSUE TITLE
How to initialize encoders with AO and VO sets

### ISSUE THREAD

**Issue by arunm95** [lordmartian/deep_avsr#18]
Hi, could you specify exactly how to initialize the AV encoders/decoders with the AO and VO trained models in the config file? I'm unclear on where to add those to the settings. Thanks!

**Comment by lordmartian** [comment]
Hi,
You will have to write a small separate code for reading the AO and VO weights files, picking the weights which you want and loading them in the AV model and finally saving them in an AV weights file. You can then initialize the AV model with this AV weights file while training.
