### ISSUE TITLE
How could I get the pretrained-weights

### ISSUE THREAD

**Issue by liuzeyang0311** [lordmartian/deep_avsr#22]
Hello, I see that you said that if I need the pretrained-weights, I can send email to 'smeetrs < at > iitb.ac.in '. But I found that this email address is an invalid email address. Could you please tell me how to solve it?

**Comment by lordmartian** [comment]
The email address is working and I do get mails on it. Be sure to replace <at> with @. Else, please check with your mail administrator.

**Comment by liuzeyang0311** [comment]
I have successfully sent the email, thank you. But I haven't received a reply yet.
