### ISSUE TITLE
the result under noisy audio

### ISSUE THREAD

**Issue by xjwla** [lordmartian/deep_avsr#27]
Hi,
 I have some questions about the result under Noisy audio. My understanding is that the WER in cases noisy audio needs to set the  'args["NOISE_PROBABILITY"] =1' in config.py . Would you please tell me if my understanding is correct . Thank you very much for your help

**Comment by lordmartian** [comment]
args["NOISE_PROBABILITY"] is the probability with which noise is added to the audio of samples while training. Setting it to 1 will make thr model train only on noisy audio samples. In order to test an already trained model with noisy audio samples, you need to set args["TEST_DEMO_NOISY"] = True.
