### ISSUE TITLE
The performance when doing curriculum learning

### ISSUE THREAD

**Issue by Flash-321** [lordmartian/deep_avsr#28]
Hi there,

Thanks a lot for your open source repo and code, I adapted your code to build a new AVNet and directly using AV data to train the model. when doing curriculum learning and the num of words = 1, my model converge at a WER of 0.55, but when I use this checkpoint to initialize num of words = 2 and start training, the model converge at a WER of 0.7, which is even worse than when the num of words = 1. I expected WER to drop after each iteration.

The question I want to ask is that did you ever encounter problems like this when you training AO or VO model?

**Comment by Flash-321** [comment]
and I will appreciate it if you could share the WER performance when you training AO model at num of words=1, thanks a lot!

**Comment by lordmartian** [comment]
Hi,
The WER increases for first few iterations and then starts reducing. I do not have the WER numbers after each iteration for any of the models now.

**Comment by Flash-321** [comment]
Thanks a lot for your reply!

> Hi,
> The WER increases for first few iterations and then starts reducing. I do not have the WER numbers after each iteration for any of the models now.

**Comment by Flash-321** [comment]
> Hi,
> The WER increases for first few iterations and then starts reducing. I do not have the WER numbers after each iteration for any of the models now.

Hi,
Do I need to adjust the INIT_LR and the FINAL_LR in each iteration?

**Comment by lordmartian** [comment]
I didn't change them for my training.

**Comment by Flash-321** [comment]
> I didn't change them for my training.

Thanks a lot!
