### ISSUE TITLE
Request from a colleague who is engaged in AVSR research like you

### ISSUE THREAD

**Issue by gmh8000** [lordmartian/deep_avsr#29]
Hello, please forgive me for not knowing your real name. 
I am a PhD student from Tianjin University in China. My name is Guo Minghao. I am currently engaged in AVSR research, and I am also reproducing an AVSR model that is the same as yours. I downloaded your code sample on github, which is very inspiring for my research. I tried to contact you according to the following email address, smeetrs<AT>iitb.ac.in, but the above email address seems to be wrong. Could you please send me the weight files of your AV, AO, VO models, I am very grateful.
My email is: 1020244029@tju.edu.cn

Thank you very much！！！
Guo minghao

**Comment by lordmartian** [comment]
Please try again by using @ instead of < AT > in the email. Mostly that should be the issue. Else please contact your mail administrator.
