### ISSUE TITLE
WER after pretraining and training

### ISSUE THREAD

**Issue by lastlap** [lordmartian/deep_avsr#30]
Hi I had a few questions about pretrain.py and train.py in AV.
1) I pretrained multiple times by changing num_words. I was able to do so upto 29 and by then I had to decrease batch size to 1 to avoid cuda OOM. I wasn't able to train for num_words = 37 as it hit cuda out of memory each time. Is there any other way than reducing batch size to solve this? (i'm using a 11gb gpu)
2) Since I wasn't able to pretrain for 37 I continued to train.py. In some other issue(closed now) you had mentioned your final pretrain wer for AV as 0.245 and after training wer as 0.168. After pretraining upto 29 words my pretrain wer was around the same as yours, but after runnning train.py i was unable to decrease it as much as you had. My final wer after train came out around 0.180. Is there anything you did after pretrain or while running train.py that helped decrease yours so much? Do you have any other suggestions to decrease wer?

**Comment by lordmartian** [comment]
Hi,
1. During AV pretraining, we kept the audio and video encoders fixed, only the AV decoder was kept trainable. If you follow this, you will not hit OOM errors during 37 words pretraining.
2. I think completing the pretraining for 37w and then training will help reduce that extra 1.2%.

**Comment by lordmartian** [comment]
Can you run the `lrs2pretrain_max_inplen_checker()` function in checker.py file for 37w? It seems that video length of one of the samples exceeds 2500 which is the length of the positional encodings. It's strange because I hadn't faced this issue when I had trained the model. Are you using LRS2 dataset or some other dataset? If the same, then there may have been some change in the dataset recently.

**Comment by lastlap** [comment]
It might be because of few changes I made which increased vid_inp length. lrs2pretrain_max_inplen_checker() returns 935 for the original code but because of few changes I made it returns 2175 now. I'm using LRS2 dataset itself.
If I increase length of positional encoding from 2500 to something > 2742 will it solve my problem? Should I pretrain from scratch again if I increase it's length?

**Comment by lordmartian** [comment]
Yes, increasing the length of the positional encodings will solve the issue. Whether to train from scratch or not depends on whether the first 2500 values of positional encodings depend on the max length or not. You can determine that from the formula of positional encodings used.

**Comment by lastlap** [comment]
The first 2500 values seem to be the same after increasing max_len. Thank you.
