### ISSUE TITLE
Pre-trained weights of the AO, VO and AV models for lip reading

### ISSUE THREAD

**Issue by CasperLindbergAtGithub** [lordmartian/deep_avsr#34]
Hi,

Is it possible to get the pre-trained weights of the AO, VO and AV models for lip reading? If you do not want to post them publicly, can you send it to my institutional email: casperl@student.chalmers.se?

Best regards,
Casper

**Comment by RaihanG** [comment]
Hi there,
Can I get pre-trained weights of the AO, VO and AV models for lip reading?
My email: raihan.goni@northsouth.edu

**Comment by lordmartian** [comment]
@CasperLindbergAtGithub @RaihanG please send an email.
