### ISSUE TITLE
Language Model Execution Never Ends

### ISSUE THREAD

**Issue by padmanabhankrishnamurthy** [lordmartian/deep_avsr#40]
While performing inference on the audio-visual model and setting `USE_LM` to `True`, the demo gets stuck and never completes. Specifically, line number 34 in `lrs2_char_lm.py` -`batch, finalStateBatch = self.lstm(batch, initStateBatch)`, executes endlessly. How can this be resolved? Thanks!

**Comment by lordmartian** [comment]
Kindly update

**Comment by padmanabhankrishnamurthy** [comment]
Hi,
I've double checked, and my input files do match all specifications (number of characters, mouth location, video duration etc.). This is evidenced by the fact that inference using greedy search and beam search without LM work fine - but the output is quite inaccurate. However, the issue continues to persist when I set USE_LM to true.

**Comment by lordmartian** [comment]
First time such an issue has been observed. 

If possible, can you please provide one of these samples that you are using? I can try to check at my end.

Also, which model are you using (AO/VO/AV)? Have you made any changes to the code (if no, can you once check with git whether any files are modified by mistake)? And are the package versions same as the ones listed in requirements?

**Comment by lordmartian** [comment]
Kindly update.

**Comment by lordmartian** [comment]
Closing issue. Re-open if required.
