### ISSUE TITLE
The Validation WER in pretrain is always 1.0

### ISSUE THREAD

**Issue by lightning830** [lordmartian/deep_avsr#42]
Hi
I trained pretrain with num_word 1,2, but the Validation WER is always 1.0.
The Training WER goes down to about 0.5, but the Validation WER does not go down.
(I've looked at other issues and changed the seed value.)

Is this correct?
If I increase the num_word in the pretrain, will the Validation WER go down?

**Comment by lordmartian** [comment]
In 'audio_visual', we use both the modalities for prediction. Check that the AOProb and VOProb is 0 (i.e AVProb=1) in valParams passed to the evaluate function in pretrain.py file. In your case, only the audio side of the model gets trained but the video side is still random and thus Val WER stays 1.

**Comment by lightning830** [comment]
Thank you for the reply. I solved it.
