### ISSUE TITLE
What does <EOS> and " " mean?

### ISSUE THREAD

**Issue by FL990** [lordmartian/deep_avsr#44]
Hi, I' working with your code.
Some question want to ask
1. What does`<EOS>` mean? End of sequence? If it's end of sequence, where is start of sequence`<SOS>`?
   And in LRS2, they slice videos, so one video present one sequence.
   Does it means that `<EOS>` and `<SOS>` is not necessary?

2. And, does `" "` means space between words?

https://github.com/lordmartian/deep_avsr/blob/2fe30359162f71f2bed1b17275122c00594ad40c/video_only/config.py#L26-L29

**Comment by lordmartian** [comment]
Yes <EOS> is for End of Sequence and " " is the space between words. If required (like in language model), we use the space as start of sequence. I don't recall now why there was a need to use <EOS> but it was necessary or useful.
