### ISSUE TITLE
Why set "AUDIO_ONLY_PROBABILITY" and "VIDEOO_ONLY_PROBABILITY" these two parameters?

### ISSUE THREAD

**Issue by gmh8000** [lordmartian/deep_avsr#46]
Hi, I noticed that your training is very much like "joint training", i.e., learning three different tasks in the same network at the same time; however, the details are not quite the same as "joint training", i.e., "joint training "does not have the above two parameters. "Joint training" trains three inputs simultaneously and then assigns different weights; your work doesn't seem to do that. Did you refer to other papers for your approach? If so, can you share it? If not, can you explain why you set it up this way?

**Comment by gmh8000** [comment]
After searching, I found the basis for you to do so, here is a relevant quote 
Shi B, Hsu W N, Lakhotia K, et al. Learning audio-visual speech representation by masked multimodal cluster prediction[J]. arXiv preprint arXiv:2201.02184, 2022.

**Comment by lordmartian** [comment]
Yes, the training is similar to joint training. I hadn't referred any papers for it nor it was supposed to be a formal joint training procedure. I wanted the end AV network to be usable with all the three cases (AO, VO, AV). So to avoid the network getting overtuned for only the AV case, I added some AO/VO training samples in between (governed by AO/VO probabilities) to kind of regularize the network. The end output values were as per expectations so I didn't dig in further to improve the joint training process.
