### ISSUE TITLE
Where is the seq2seq model at 'audi_visual' or 'video only'?

### ISSUE THREAD

**Issue by HaoDot** [lordmartian/deep_avsr#48]
Hi @lordmartian 

Thanks for your generous sharing! It seems that there is no accomplishment of `Transformer seq2seq` @ Fig. 2. I wonder if I have miss something important. If so, could you help me to figure it out? 

Thanks for your time!

**Comment by lordmartian** [comment]
As stated in Readme, only the TM-CTC model is implemented from the paper. TM-seq2seq is not implemented.
