### ISSUE TITLE
RuntimeError: cublas runtime error

### ISSUE THREAD

**Issue by crucian-star** [lordmartian/deep_avsr#52]
Hello, I reported this error when preprocessing :
RuntimeError: cublas runtime error : the GPU program failed to execute at C:/w/1/s/windows/pytorch/aten/src/THC/THCBlas.cu:331
It seems that cuda10.0 does not match, can I reproduce this code in cuda12.0？

Looking forward to your reply, thank you！

**Comment by smeetrs** [comment]
Hi,

I am sorry but I won't be able to help on this as I am not aware of this issue.

You can try using cuda 12.0. I haven't used the 12.0 version so not sure what changes would be required.

**Comment by crucian-star** [comment]
Thank you for your reply! 
I did not change the code, tried to use cuda11.7, can successfully run!
