### ISSUE TITLE
audio-visual.pt file

### ISSUE THREAD

**Issue by zlwxwxsdzrx** [lordmartian/deep_avsr#55]
Hello, thanks for sharing the code.
I have a question, is the audio-visual.pt file you uploaded already integrated with the weights of AO and VO?

**Comment by smeetrs** [comment]
I didn't fully understand your question. Can you please elaborate? More specifically, what do you mean by 'integrated'?

**Comment by zlwxwxsdzrx** [comment]
I'm sorry my question wasn't stated clearly.
As you wrote in 'readme' : 

“We train the AO and VO models first. We then initialize the AV model with weights from the trained AO and VO models as follows: AO Audio Encoder → AV Audio Encoder, VO Video Encoder → AV Video Encoder, VO Video Decoder → AV Joint Decoder.”

Is the audio-visual.pt file already initialized with the pre-trained AO and VO models? I want to start training AV models, I don't know if I should write additional code to merge AV models using the weights of the trained AO and VO models, or just use the audio-visual.pt you uploaded?

**Comment by smeetrs** [comment]
You can directly use the uploaded file. The weights in the audio-visual.pt file are for the AV model which was initialized with AO and VO model weights and then fully trained using AV data. Hope that answers your query.

**Comment by zlwxwxsdzrx** [comment]
Ok, thank you very much for your reply！
