### ISSUE TITLE
Details of the pretrained visual frontend and language models?

### ISSUE THREAD

**Issue by kasri-mids** [LordMartian/deep_avsr#7]
Hi,
Can you provide any more details on the pretrained visual frontend and LM's? Datsets used in the pretrained model?

Thanks!

**Comment by LordMartian** [comment]
Hi,
I have taken the pretrained weights of the visual frontend and language model from the GitHub repository of [this](https://arxiv.org/abs/1806.06053) paper (Ref. 1). Kindly refer the paper for all the details regarding these models.
